### ISSUE TITLE
Add a LICENSE to repository

### ISSUE THREAD

**Issue by korenmiklos** [jonathandroth/HetEventStudies#1]
Hi @jonathandroth, I am citing your paper and test dataset in my Stata package. Can you add a LICENSE to clarify whether I can include the `df.dta` in my Stata package on SSC?

**Comment by korenmiklos** [comment]
See here: https://github.com/codedthinking/eventstudy/tree/eventbaseline

**Comment by jonathandroth** [comment]
Good call. Added MIT license (so yes, you can share). Thanks for citing!
